export default {
    AUTH_ENDPOINTS: {
        LOGIN: "/auth/login",
        LOGOUT: "/auth/logout",
        REGISTER: "/auth/register",
        REFRESH_TOKEN: "/auth/refresh",
        ME: "/users/myinfo",
        UPDATE_ME: "/users/update",
        UPDATE_AVATAR: "/users/avatar",
        UPDATE_PASSWORD: "/users/password",
    },
    USER_ENDPOINTS: {
        GET_BY_ID: (id: string) => `/users/${id}`,
        GET_ALL: "/users",
        SEARCH: "/users/search",
    },
    POST_ENDPOINTS: {
        GET_ALL: "/posts",
        GET_BY_ID: (id: string) => `/posts/${id}`,
        CREATE: "/posts",
        UPDATE: (id: string) => `/posts/${id}`,
        DELETE: (id: string) => `/posts/${id}`,
        GET_BY_GROUP: (groupId: string) => `/posts/group/${groupId}`,
        GET_BY_USER: (userId: string) => `/posts/user/${userId}`,
        SEARCH: "/posts/search",
    },
    COMMENT_ENDPOINTS: {
        GET_BY_POST: (postId: string) => `/comments/post/${postId}`,
        CREATE: "/comments",
        UPDATE: (id: string) => `/comments/${id}`,
        DELETE: (id: string) => `/comments/${id}`,
    },
    INTERACTION_ENDPOINTS: {
        CREATE_OR_UPDATE: "/interactions",
        GET_BY_POST: (postId: string) => `/interactions/post/${postId}`,
    },
    GROUP_ENDPOINTS: {
        GET_ALL: "/groups",
        GET_BY_ID: (id: string) => `/groups/${id}`,
        CREATE: "/groups",
        UPDATE: (id: string) => `/groups/${id}`,
        DELETE: (id: string) => `/groups/${id}`,
        JOIN: (id: string) => `/groups/${id}/join`,
        LEAVE: (id: string) => `/groups/${id}/leave`,
        GET_MEMBERS: (id: string) => `/groups/${id}/members`,
        GET_MY_GROUPS: "/groups/my",
        SUGGESTED: "/groups/suggested",
    },
    FRIENDSHIP_ENDPOINTS: {
        GET_FRIENDS: "/friendships/friends",
        GET_REQUESTS: "/friendships/requests",
        GET_SENT_REQUESTS: "/friendships/sent",
        SEND_REQUEST: "/friendships/request",
        ACCEPT: (id: string) => `/friendships/accept/${id}`,
        REJECT: (id: string) => `/friendships/reject/${id}`,
        UNFRIEND: (id: string) => `/friendships/unfriend/${id}`,
        BLOCK: (userId: string) => `/friendships/block/${userId}`,
        UNBLOCK: (userId: string) => `/friendships/unblock/${userId}`,
        GET_BLOCKED: "/friendships/blocked",
        GET_STATUS: (userId: string) => `/friendships/status/${userId}`,
    },
    CHAT_ENDPOINTS: {
        SEND_MESSAGE: "/chat/send",
        GET_MESSAGES: "/chat/messages",
        GET_CONVERSATIONS: "/chat/conversations",
        GET_CONVERSATION: (id: string) => `/chat/conversation/${id}`,
        CREATE_GROUP: "/chat/group",
        ADD_MEMBER: "/chat/group/member",
        REMOVE_MEMBER: "/chat/group/member/remove",
        MARK_READ: "/chat/read",
    },
    FILE_ENDPOINTS: {
        UPLOAD_IMAGE: "/files/upload/image",
        UPLOAD_AVATAR: "/files/upload/avatar",
        UPLOAD_DOCUMENT: "/files/upload/document",
        DELETE: "/files/delete",
    },
    NOTIFICATION_ENDPOINTS: {
        GET_ALL: "/notifications",
        MARK_READ: (id: string) => `/notifications/${id}/read`,
        MARK_ALL_READ: "/notifications/read-all",
    },
} as const;
